# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: integration-wa-gateway2-stie

on:
  push:
    branches: ["updated-master"]
  pull_request:
    branches: ["updated-master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm install && npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    # needs: build  # Menandakan bahwa job ini memerlukan penyelesaian dari job "build"
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy script. Deploy to ghcr.io as `wa-gateway2-stie` package.
        # - name: Run deploy script
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          chmod +x ./build-push-backend.sh
          ./build-push-backend.sh
